Simplify wrapping of pointers to members
ska-sa/spead2 pull request #266
Opened 2023-09-05 12:57 UTC by bmerry

I did some microbenching and found no evidence that the SPEAD2_PTMF wrapper was improving performance at all, compared to just passing the pointer-to-member-function to pybind11, even though the latter involves making a call via a pointer (bad for branch prediction). So I've eliminated the SPEAD2_PTMF macro entirely, and simplified SPEAD2_PTMF_VOID to use a more obvious approach. The latter also isn't needed for any const member functions so I eliminated that support too.

2023-09-05 12:57 UTC, bmerry commented
@sjperkins I don't seem to be able to assign to you, but would you mind giving this a quick look?

2023-09-06 07:57 UTC, sjperkins requested changes
I think it would be useful to retain some earlier comments, but otherwise it looks fine to me.

2023-09-06 07:57 UTC, sjperkins commented on include/spead2/py_common.h
> +auto discard_result(R (C::*func)(Args...))
I think it would be helpful to retain the comment about `T` and `C` as separate but similar, because I had to think about it again and was helped by the removed the comment

2023-09-06 11:57 UTC, bmerry commented on include/spead2/py_common.h
> +auto discard_result(R (C::*func)(Args...))
Fair point. See if you're happy with the updated version.

2023-09-06 12:33 UTC, bmerry commented
Thanks for reviewing.

2023-09-06 14:03 UTC, merged