Shift a couple of stages from Jenkinsfile into Dockerfile
ska-sa/spead2 pull request #364
Opened 2024-12-02 14:00 UTC by james-smith-za

The Jenkins job on our new deployment is running Docker containers with the option `-u 1000:1000` instead of `-u 0:0` which results in permissions issues when doing administrative things such as using `apt-get` to install stuff.

So this commit moves the install stages of the test run into a Dockerfile, so that the image which is all nicely configured can then be used to run the tests.

Relates to NGC-1447.

2024-12-02 14:35 UTC, james-smith-za commented
This job is working on the Jenkins test instance barring the fact that the agent doesn't have multicast loopback (which I haven't configured yet on the test agent), so I guess it's a good sign?

2024-12-02 14:39 UTC, james-smith-za commented
The test passes on old Jenkins though so that's helpful.

2024-12-03 05:51 UTC, bmerry commented
The linting checks are failing on Github Actions.

2024-12-03 06:05 UTC, bmerry requested changes

2024-12-03 20:31 UTC, james-smith-za commented
Fair points all round, and I have addressed your feedback as far as I am able. I am now running into issues with files not being found in meson:
```
22:19:11    + meson setup /var/jenkins/workspace/ead2_ngc-1447-jenkins-dockerfile /var/jenkins/workspace/ead2_ngc-1447-jenkins-dockerfile/.mesonpy-4tmu33hl -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dtools=disabled -Dunit_test=disabled -Dcuda=disabled -Dgdrapi=disabled -Dcap=disabled -Dpython=true --native-file=ci.ini -Dibv=enabled -Dibv_hw_rate_limit=enabled -Dmlx5dv=enabled --native-file=/var/jenkins/workspace/ead2_ngc-1447-jenkins-dockerfile/.mesonpy-4tmu33hl/meson-python-native-file.ini
22:19:11    Could not find any valid candidate for native files: ci.ini
22:19:11  
22:19:11    ERROR: Cannot find specified native file: /var/jenkins/workspace/ead2_ngc-1447-jenkins-dockerfile/.mesonpy-4tmu33hl/meson-python-native-file.ini
22:19:11    error: subprocess-exited-with-error
```

see [here](https://jenkins-test.cbf.mkat.karoo.kat.ac.za/job/spead2/job/ngc-1447-jenkins-dockerfile/15/console).

I'm not quite clear as to which file is missing though: it looks as though it's complaining both about the `ci.ini` file and the `/var/jenkins/..../meson-python-native-file.ini`. The former looks to me as though it gets explicitly created somewhere but the latter I'm not sure about.

2024-12-04 09:44 UTC, bmerry commented
I'll investigate.

2024-12-04 09:53 UTC, bmerry commented
My guess would be that it's because install-sys-pkgs.sh is creating the ci.ini in $HOME, but $HOME during the docker build probably doesn't match the $HOME during the test.

I think let me see if I can rework things to write the ci.ini in the workspace rather than somewhere in $HOME, since I'm not sure we can rely on having a $HOME in the Jenkins case (particularly if the agent doesn't use UID 1000).

2024-12-04 11:35 UTC, bmerry requested changes
Looks good, just some corrections to the copyright block. Feel free to merge after fixing those.

2024-12-04 11:35 UTC, bmerry commented on .ci/Dockerfile
> +# Copyright (c) 2024, National Research Foundation (SARAO)
```suggestion
# Copyright 2024 National Research Foundation (SARAO)
```
for consistency with other files.

2024-12-04 11:35 UTC, bmerry commented on .ci/Dockerfile
> +#
```suggestion
```

2024-12-04 11:56 UTC, james-smith-za commented on .ci/Dockerfile
> +# Copyright (c) 2024, National Research Foundation (SARAO)
I thought I'd fixed this.

2024-12-04 11:57 UTC, james-smith-za commented on .ci/Dockerfile
> +ENV PATH=/venv/bin:$PATH
Are you looking at the right commit? It's marked as outdated.

2024-12-04 11:58 UTC, merged

2024-12-04 12:03 UTC, bmerry commented on .ci/Dockerfile
> +ENV PATH=/venv/bin:$PATH
I think that's a comment I'd made earlier but didn't submit, that got swept up into my recent review.

2024-12-04 12:23 UTC, james-smith-za commented on .ci/Dockerfile
> +ENV PATH=/venv/bin:$PATH
Ah, that does make sense.