Drop Python 3.5 support
ska-sa/spead2 pull request #95
Opened 2020-09-28 08:16 UTC by bmerry

It's about to be end-of-life, and removing it also allows dropping the explicit `loop` argument (passing it down to asyncio functions is deprecated in recent versions of Python). I figure this is a good time to remove that argument since I'm making other breaking changes in spead2 3.0.

It's probably worth reviewing the commits individually, because the pyupgrade commit is long but completely mechanical.

2020-09-28 09:55 UTC, ludwigschwardt requested changes
Just one niggle (although I haven't searched for any errant loop variables in the rest of the codebase).

2020-09-28 09:55 UTC, ludwigschwardt commented on spead2/__init__.py
> +                    raise ValueError(f'illegal format ({code}, {length})')
Nice to see automatic upgrades to f-strings. I should run pyupgrade on katpoint too...

2020-09-28 09:55 UTC, ludwigschwardt commented on spead2/test/test_recv.py
> -                Item(0x1234, 'Hello world'.encode('ascii'))
Interesting that `.encode('ascii')` was needed in the first place.

2020-09-28 09:55 UTC, ludwigschwardt commented on spead2/test/test_passthrough_asyncio.py
>          return ret
There is no `ret` to return. You can probably just remove the statement, or is it an error?

2020-09-28 10:20 UTC, bmerry commented on spead2/test/test_recv.py
> -                Item(0x1234, 'Hello world'.encode('ascii'))
I think it might date from Python 2 support - possibly before `b'Hello world'` was accepted in Python 2.

2020-09-28 10:22 UTC, bmerry commented on spead2/test/test_passthrough_asyncio.py
>          return ret
I've already fixed this in a subsequent PR. I'd rather not deal with trying to backport it.

2020-09-28 11:52 UTC, ludwigschwardt commented on spead2/test/test_passthrough_asyncio.py
>          return ret
Saw that in passing 👍

2020-09-28 11:53 UTC, ludwigschwardt approved these changes

2020-09-30 13:20 UTC, bmerry commented
Merged manually (by merging a downstream branch), so closing.

2020-09-30 13:20 UTC, closed without merging